### ISSUE TITLE
Cherry pick ca-bundle fix from XeroApi

### ISSUE THREAD

**Issue by naderman** [elliotchance/xero-api#8]
The commit https://github.com/XeroAPI/XeroOAuth-PHP/commit/1fba72b70e4ff8f27c9344b98db5a902eae4a1b2 fixes the curl ca bundle, as newer versions have removed necessary root/intermediary certs. Please cherry-pick that  commit into here and tag a new release, thanks.

**Comment by elliotchance** [comment]
`v0.6` and `v0.6.1` pulled from the upstream are available now.
